feat(pantry): added joining pantry using invite code
skanna-app/service pull request #20
Opened 2021-07-21 17:06 UTC by Swiftwork

Closes #19

2021-07-30 12:33 UTC, lowekoz requested changes

2021-07-30 12:33 UTC, lowekoz commented on internal/app/pantry.go
> +	pantryToJoin, err := app.pantry.GetByInviteCode(code)
Endpoint uses URL ".../pantries/invitations/:code" with body 
{
    "inviteCode": "some code",
    "user": "some user"
}
Here inviteCode in body and :code in URL refers to the same code. Maybe rename both to code or inviteCode to avoid ambiguity?

2021-07-30 12:33 UTC, lowekoz commented on internal/app/pantry.go
> +func (app *App) PostPantriesPantryIdInviteCodes(ctx echo.Context, pantryId string) error {
Tested with postman:

before : 02349875639877
__after : 2793236849618

It seems that the newly generated code is not the same length as initial, is this intentional?

2021-08-05 15:29 UTC, Swiftwork commented on internal/app/pantry.go
> +	pantryToJoin, err := app.pantry.GetByInviteCode(code)
Good catch, I think I missed removing one here

2021-08-05 15:30 UTC, Swiftwork commented on internal/app/pantry.go
> +func (app *App) PostPantriesPantryIdInviteCodes(ctx echo.Context, pantryId string) error {
This is probably because of the padding of zeroes before the ean13 code. I will revise and see if I can make that clearer.

2021-08-07 17:57 UTC, Swiftwork commented on internal/app/pantry.go
> +	pantryToJoin, err := app.pantry.GetByInviteCode(code)
Hmm I can not find this, I think I might have resolved this previously then.

2021-09-10 17:27 UTC, merged