feat(product): #4 open food facts enrich
skanna-app/service pull request #7
Opened 2021-06-18 13:20 UTC by lowekoz

**--- DRAFT ---**
Adds Open Food Facts as secondary data base to enrich dabas data
![image](https://user-images.githubusercontent.com/72736642/122566330-b867d500-d047-11eb-92b3-c29a5bd2fd93.png)

**TODO:**
- improve error handling ?
- bug-test against different GTINs
- improve OFF model data handling & extraction

2021-06-30 11:28 UTC, lowekoz commented on internal/product/repo/postgres/postgres.go
> +		// Send no error in case of not found in data base
remove comment

2021-07-02 10:36 UTC, Swiftwork requested changes

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +		}
```golang
if OFFIngredient.Share == 34
  OFFIngredient.Share = OFFIngredient.Share[1,len-1]
  
f64tmp, err := strconv.ParseFloat(string(nw), 32)
if err != nil {
  f64tmp = 0
}
share = float32(f64tmp)
```

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +			Name:        OFFIngredient.Name,
Clean up name, remove country code, change to sentence case, and replace hyphens with spaces?

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +			Description: OFFIngredient.Description, // Sometimes just another language for the same thing :/
Remove

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +			Name:        OFFIngredient.Name,
Create formatters in `/internal/utils/formatters/strings.go`

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +	for _, el := range OFFProduct_Object.Product.AllergenTags {
v

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +	for _, el := range OFFProduct_Object.Product.Markings {
v

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +		OFFProduct_Object.Product.Countries = append(OFFProduct_Object.Product.Countries, "") // Sql not null condition
Will be handled later using country code util. Add a todo.

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +	var OFFSheet string
off -> openfoodfacts

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +	var cheat string
Write todo: improve concept

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/repo/postgres/model.go
> +	OFFSheet                string    `db:"off_sheet"`
off ->  openfoodfacts

2021-07-02 10:36 UTC, Swiftwork commented on internal/product/units/units.go
> +package units
Move to `/internal/utils/units/units.go`

2021-07-02 10:36 UTC, Swiftwork commented on internal/validator/validator.go
>  // UUIDRegexp pattern matching an UUID
move to `/internal/utils/validators/validators.go`

2021-07-05 13:48 UTC, lowekoz commented on internal/product/repo/openfoodfacts/model.go
> +	if len(OFFProduct_Object.Product.NutritionClaim) > 0 {
len() function handles null case. Do you want null case handled explicitly for clarity anyway?

![image](https://user-images.githubusercontent.com/72736642/124480655-ca67a880-dda7-11eb-8a6a-558840238365.png)

2021-07-09 09:01 UTC, lowekoz commented on internal/utils/formatters/strings.go
> +		if !(tag == "sv") || !(tag == "en") {
!(tag == "sv" || tag == "en")

2021-07-09 17:18 UTC, Swiftwork requested changes
NEARLY THERE! 🚀  PS: resolve all comments that you have fixed :)

2021-07-09 17:18 UTC, Swiftwork commented on db/schema.sql
>  	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
Incorrect indentation?

2021-07-09 17:18 UTC, Swiftwork commented on internal/product/repo/aggregator/aggregator.go
> +		// TODO: Do not initialize values, use product/standard instead
Is this comment still relevant?

2021-07-09 17:18 UTC, Swiftwork commented on internal/product/repo/dabas/model.go
> +		article.Contents[0].Amount, article.Contents[0].Type = units.ConvertToStandard(article.Contents[0].Amount, article.Contents[0].Type, article.GTIN)
I think we discussed not sending pointers, but rather values. The reasoning was that there are negligible performance differences, but is much easier to follow (more immutable behavior).

2021-07-09 17:18 UTC, Swiftwork commented on internal/product/repo/dabas/model.go
> +		article.Contents[0].Amount, article.Contents[0].Type = units.ConvertToStandard(article.Contents[0].Amount, article.Contents[0].Type, article.GTIN)
Also not a fan of adding GTIN as a parameter. This makes the function too coupled with products. If it's for logging purposes do the logging in this file instead.

2021-07-09 17:18 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +	if len(OFFProduct_Object.Product.NutritionClaim) > 0 {
Great! Leave it as is.

2021-07-09 17:18 UTC, Swiftwork commented on internal/product/repo/openfoodfacts/model.go
> +			Name:        OFFIngredient.Name,
Let's handle this later in another PR so that we can close this. Write a `todo` comment.

2021-07-09 17:18 UTC, Swiftwork commented on internal/utils/units/units.go
> +	"milliliters": "ml",
British spelling also includes litres

2021-07-09 17:18 UTC, Swiftwork commented on internal/utils/units/units.go
> +		log.Println("Unknown unit: " + unit + " for product GTIN: " + gtin)
Remove GTIN. Unnecessary coupling to products.

2021-07-14 07:12 UTC, Swiftwork approved these changes

2021-07-14 09:16 UTC, merged